# Generated by Django 4.2.6 on 2023-10-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
