# Generated by Django 4.2.6 on 2023-10-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_course_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='preview',
            new_name='preview_course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='description_lesson',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='name_lesson',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='preview',
            new_name='preview_lesson',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video_link',
            new_name='video_link_lesson',
        ),
    ]
