# Generated by Django 4.2.6 on 2023-10-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscribed',
        ),
    ]
