# Generated by Django 4.2.6 on 2023-10-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_description_course_description_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description_course',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_lesson',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
