# Generated by Django 4.2.6 on 2023-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_description_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_lesson',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
    ]
